repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--safe]
  # pyhton -m unittest
  - repo: local
    hooks:
      - id: unittests
        name: run unit tests
        entry: tox
        language: system
        pass_filenames: false
        # args: ["discover"]